### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by ghost** [gbro115/homebridge-roomba690#2]
When attempting to install, I get this error. 

ERR: MODULE_NOT_FOUND
ERR: Cannot find module 'internal/util/types'

**Comment by gbro115** [comment]
@brentleeper are you having other issues with homebridge? Someone reported a similar issue here https://github.com/nfarina/homebridge/issues/1603

**Comment by ghost** [comment]
I did a complete reinstall of my system. After further research, I think this issue is related to an issue with my NPM install.

**Comment by gbro115** [comment]
@brentleeper- can I mark this as closed?

**Comment by ghost** [comment]
Yes, thank you

**Comment by gbro115** [comment]
Thanks
