### ISSUE TITLE
Turning Roomba off when it is running results in it stopping and then starting back up

### ISSUE THREAD

**Issue by CappyD** [gbro115/homebridge-roomba690#4]
I just installed this plug-in and I am able to check the status and start Roomba from the Home app in iOS just fine. But I noticed that if I start Roomba and then tell it to stop, it does stop for a few seconds and then starts back up. In the Home app, it still shows as "off". If I take it again, Roomba stops and stays stopped, but now it shows as "on" in the Home app. Seems there's a problem there.

**Comment by CappyD** [comment]
Only looking at it when this happens, it restarts with the Home light flashing so Off apparently means to go to home base.

**Comment by gbro115** [comment]
Archiving repo. Closing.
