### ISSUE TITLE
Add a "return home" capability

### ISSUE THREAD

**Issue by CappyD** [gbro115/homebridge-roomba690#5]
In addition to On and Off commands, it really needs a Return to Home Base command since Off makes it stop where it is (except for the problem with this that I just entered).

**Comment by CappyD** [comment]
It seems that Off seems to tell it to find it's home base. odd though that it stops. But then it restarts with the Home light flashing, so it appears to be looking for home.

**Comment by gbro115** [comment]
Archiving repo. Closing.
