### ISSUE TITLE
Homebridge goes offline if Roomba is disconnectedf

### ISSUE THREAD

**Issue by jnanes** [gbro115/homebridge-roomba690#6]
If my roomba is offline (battery dies, etc), the rest of my Homebrdige setup becomes inoperable and goes offline. Simply getting the roomba back online fixes the problem. Is there any way this can be resolved so that hombridge simply bypasses the roomba if it is offline?

**Comment by stevenliuyi** [comment]
I also encountered exactly the same issue recently.  In the end, I fixed it by implementing a response timeout feature. Here is my fork: https://github.com/stevenliuyi/homebridge-irobot-roomba690.

**Comment by gbro115** [comment]
Archiving repo. Closing.
