### ISSUE TITLE
Device shows no response in home app

### ISSUE THREAD

**Issue by bjbech** [gbro115/homebridge-roomba690#7]
Device appears in the home app but shows as ‘No Response’ after being installed on homebridge.  Has an update to the Roomba broke compatibility?

**Comment by jsit** [comment]
For me too. In Homebridge's log I get:

```
[Roomba] Power state requested for Roomba
```

Then nothing. I'm using a Roomba 675 however, so this may be affecting it (though dorita980 is said to work with the 675).

**Comment by jsit** [comment]
A simple dorita980 node script is working for me, however:

```javascript
var dorita980 = require('dorita980');

var myRobotViaLocal = new dorita980.Local('XXX', 'XXX', 'XXX');

myRobotViaLocal.on('connect', init);

function init () {
          myRobotViaLocal.clean()
          .then(() => myRobotViaLocal.end())
          .catch(console.log);
}
```

This script works fine, but the Homebridge plugin does not. Can't locate the issue.

**Comment by jsit** [comment]
I figured it out -- this plugin is using an outdated version of dorita980.

**Comment by angle52** [comment]
Is there anyway to get this working until the dependency is fixed? i'm in the same boat.

**Comment by gbro115** [comment]
Archiving repo. Closing.
