### ISSUE TITLE
Unable to communicate to Roomba via HOOBS

### ISSUE THREAD

**Issue by jnanes** [gbro115/homebridge-roomba690#9]
I have the plugin installed/configured on 2 homebridge hosts. My instance running on HOOBS, cannot get any status updates etc. I can ping the roomba from the host but the homebridge logs hang at attempts to get status updates. 

I verified dorita980, etc are installed.

[Homebridge] [12/22/2019, 11:22:14 AM] Service is running on port 51826.
[Homebridge] [12/22/2019, 11:22:40 AM] [Roomba123] Power state requested for Roomba
[Homebridge] [12/22/2019, 11:22:40 AM] [Roomba123] Battery level requested for Roomba
[Homebridge] [12/22/2019, 11:22:40 AM] [Roomba123] Charging status requested for Roomba
[Homebridge] [12/22/2019, 11:22:43 AM] [Roomba123] Power state requested for Roomba
[Homebridge] [12/22/2019, 11:22:43 AM] [Roomba123] Battery level requested for Roomba
[Homebridge] [12/22/2019, 11:22:43 AM] [Roomba123] Charging status requested for Roomba

Again, my other homebridge host works just fine so I know my BLID, etc are correct.  Any pointers would be helpful.

**Comment by gbro115** [comment]
Archiving repo. Closing.
